Learning/Models/Invoice.cs
using System.ComponentModel.DataAnnotations;

namespace Learning.Models
{
    public class Invoice
    {
        [Key]
        public int Id { get; set; }
        public string? CustomerName { get; set; }
        public DateTime? DateOfCreation { get; set; }
        public DateTime? DueDate { get; set; }
        public decimal? Amount { get; set; }
        public string? Status { get; set; }
        public string? NID { get; set; }


    }
}

Learning/Controllers/Api/InvoiceController.cs
using Learning.Models;
using Learning.NewFolder;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Learning.Controllers.Api
{
    [Route("api/[controller]")]
    [ApiController]
    public class InvoiceController : ControllerBase
    {
        private readonly ApplicationDbContext _applicationDbContext;

        public InvoiceController(ApplicationDbContext applicationDbContext)
        {
            _applicationDbContext = applicationDbContext;
        }
        [HttpPost]
        [Authorize(AuthenticationSchemes = JwtBearerDefaults.AuthenticationScheme)]
        public IActionResult CreateInvoice([FromBody] Invoice model) 
        {

            // Add the new invoice to the database
            _applicationDbContext.invoice.Add(model);
            _applicationDbContext.SaveChanges();

            // Redirect the user back to the table of invoices
            return RedirectToAction("Invoice", "Accounts", new { isAdmin = true });

        }
        [HttpDelete]
        [Authorize(AuthenticationSchemes = JwtBearerDefaults.AuthenticationScheme)]
        public async Task<IActionResult> DeleteInvoice([FromQuery] int id)
        {
            try
            {
                var invoice = await _applicationDbContext.invoice.FindAsync(id);

                if (invoice != null)
                {
                    _applicationDbContext.invoice.Remove(invoice);
                    await _applicationDbContext.SaveChangesAsync();
                    return Ok(); // Assuming successful deletion, returning 200 OK
                }
                else
                {
                    return NotFound();
                }
            }
            catch (Exception ex)
            {
                return StatusCode(500, "An error occurred while processing your request.");
            }
        }
        [Authorize(AuthenticationSchemes = JwtBearerDefaults.AuthenticationScheme)]
        [HttpPut]
        public IActionResult Edit([FromBody] Invoice invoice, [FromQuery] int id)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            try
            {
                if (invoice != null)
                {
                    Console.WriteLine("invoice  {0}", invoice);

                    Console.WriteLine("invoice id {0}", invoice.Id);

                    var existingInvoice = _applicationDbContext.invoice.Find(id);
                    Console.WriteLine("existingInvoiceee {0}", existingInvoice);

                    if (existingInvoice != null)
                    {
                        // Update the properties of the existing invoice object
                        existingInvoice.CustomerName = invoice.CustomerName;
                        existingInvoice.DateOfCreation = invoice.DateOfCreation;
                        existingInvoice.DueDate = invoice.DueDate;
                        existingInvoice.Amount = invoice.Amount;
                        existingInvoice.Status = invoice.Status;

                        Console.WriteLine("existingInvoice inside  {0}", existingInvoice);


                        _applicationDbContext.Update(existingInvoice);


                        // Save the changes to the database
                        _applicationDbContext.SaveChanges();
                    }
                    return Ok(); // Return a success status code (200 OK)
                }
                else
                {
                    return BadRequest("Invoice object is null");
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine("An error occurred: {0}", ex.Message);
                return StatusCode(500, "An error occurred while processing your request.");
            }
        }


        [HttpGet]
        [Authorize(AuthenticationSchemes = JwtBearerDefaults.AuthenticationScheme)]
        [Route("test")]
        public IActionResult Test()
        {
            return Ok();
        }
    }
}

Learning/Controllers/PaymentController.cs
using Learning.NewFolder;
using Microsoft.AspNetCore.Mvc;
using Stripe;
using Stripe.Checkout;
using System.Security.Cryptography;
using System.Xml.Linq;

namespace Learning.Controllers
{
    public class PaymentController : Controller
    {

        private readonly ApplicationDbContext _applicationDbContext;

        public PaymentController(ApplicationDbContext applicationDbContext)
        {
            _applicationDbContext = applicationDbContext;
        }

        public IActionResult CreateCheckoutSession(string invoiceId, decimal amount, string name , string nid )
        {

            //make it to show the amoaun tto be payed 

            var options = new SessionCreateOptions
            {
                PaymentMethodTypes = new List<string>
        {
            "card",
        },
                LineItems = new List<SessionLineItemOptions>
        {
            new SessionLineItemOptions
            {
                PriceData = new SessionLineItemPriceDataOptions
                {
                    UnitAmount = (long)amount * 100, // Example amount in cents
                    Currency = "usd", // Example currency
                    ProductData = new SessionLineItemPriceDataProductDataOptions
                    {
                        Name = "Invoice #" + invoiceId,
                    },
                },
                Quantity = 1,
            },
        },
                Mode = "payment", // Specify the mode as "payment"
                SuccessUrl = $"https://localhost:7152/Payment/UpdatePaymentStatus?invoiceId={invoiceId}&name={name}&nid={nid}",
                CancelUrl = $"https://localhost:7152/Accounts/UserLogin?name={name}&isAdmin=false&nid={nid}",    
            };

            var service = new SessionService();
            var session = service.Create(options);

            return Redirect(session.Url);
        }

        public IActionResult UpdatePaymentStatus( int invoiceId, string name, string nid)
        {

            var invoice = _applicationDbContext.invoice.Find(invoiceId);

            if (invoice != null)
            {
                 invoice.Status = "Paid";
                _applicationDbContext.SaveChanges();
            }
            return Redirect($"https://localhost:7152/Accounts/UserLogin?name={name}&isAdmin=false&nid={nid}");
        }


    }
}

Learning/Controllers/ProfileController.cs
using Learning.Models;
using Learning.NewFolder;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Learning.Controllers
{
    public class ProfileController : Controller
    {

        private readonly ApplicationDbContext _context;

        public ProfileController(ApplicationDbContext context)
        {
            _context = context;
        }
        [HttpGet]
        public IActionResult Index(string nid)
        {
            var user = _context.login.FirstOrDefault(u => u.NID == nid);
            if (user == null)
            {
                return NotFound();
            }

            return PartialView(user);
        }

        [HttpPost]
        public IActionResult SaveProfile(LoginModel model)
        {

            // Retrieve the current user's login record from the database
            LoginModel user = _context.login.FirstOrDefault(u => u.Email == model.Email);

            // Update the user's profile with the new data
                user.Age = model.Age;
                user.Gender = model.Gender;
                user.CellPhone = model.CellPhone;
                user.City = model.City;
                user.State = model.State;

                // Save changes to the database
                _context.SaveChanges();



            return RedirectToAction("UserLogin", "Accounts", new
            {
                name = user.Name,
                isAdmin = user.isAdmin,
                nid = user.NID
            });
        }
    }
}

Learning/Views/Accounts/EditInvoice.cshtml
@model Learning.Models.Invoice

@{
    ViewBag.Title = "Edit Invoice";
}

<h2>Edit Invoice</h2>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.Id) <!-- Assuming Id is the identifier of the invoice -->

    <div class="form-group">
        @Html.LabelFor(model => model.CustomerName)
        @Html.TextBoxFor(model => model.CustomerName, new { @class = "form-control" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DateOfCreation)
        @Html.TextBoxFor(model => model.DateOfCreation, new { @class = "form-control" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DueDate)
        @Html.TextBoxFor(model => model.DueDate, new { @class = "form-control" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Amount)
        @Html.TextBoxFor(model => model.Amount, new { @class = "form-control" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Status)
        @Html.TextBoxFor(model => model.Status, new { @class = "form-control" })
    </div>

    <button type="submit" class="btn btn-primary">Save</button>
}

Learning/Views/Accounts/InvoiceUser.cshtml
@{
    ViewData["Title"] = "InvoiceUser";
}

<div class="contracts-table" id="contractsContent">
    <h2>Invoices</h2>
    <table class="table table-striped" id="pagination">
        <thead>
            <tr>
                <th>Id</th>
                <th>Customer Name</th>
                <th>Date of Creation</th>
                <th>Due Date</th>
                <th>Amount</th>
                <th>NID</th>
                <th>Status</th>
                <th>Action</th> <!-- Add a new column for action -->
            </tr>
        </thead>
        <tbody>
            @if (Model != null)
            {
                @foreach (var invoice in Model)
                {
                    <tr>
                        <td>@invoice.Id</td>
                        <td>@invoice.CustomerName</td>
                        <td>@invoice.DateOfCreation</td>
                        <td>@invoice.DueDate</td>
                        <td>@invoice.Amount</td>
                        <td>@invoice.NID</td>
                        <td>@invoice.Status</td>
                        <td>
                            @if (invoice.Status != "Paid")
                            {
                                <a class="pay-btn" asp-controller="Payment" asp-action="CreateCheckoutSession" asp-route-invoiceId="@invoice.Id" asp-route-amount="@invoice.Amount" asp-route-name="@invoice.CustomerName" asp-route-nid="@invoice.NID">Pay</a>
                            }
                        </td>

                    </tr>
                }
            }
        </tbody>
    </table>
</div>

Learning/Views/Accounts/Login.cshtml
@model Learning.Models.LoginModel

<style>
    .form-group {
        margin-bottom: 20px;
    }

    label {
        font-weight: bold;
    }

    .btn-primary {
        background-color: #007bff;
        border-color: #007bff;
    }

        .btn-primary:hover {
            background-color: #0056b3;
            border-color: #0056b3;
        }

    .btn-register {
        background-color: #28a745;
        border-color: #28a745;
    }

        .btn-register:hover {
            background-color: #218838;
            border-color: #218838;
        }
</style>



<h2>User Login</h2>


<form method="post">

    <input type="hidden" id="LoginViewModelToken" asp-for="Token" />
    <div class="form-group">
        <label asp-for="Email">Email Address</label>
        <input asp-for="Email" class="form-control" />
        <span asp-validation-for="Email" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Password">Password</label>
        <input asp-for="Password" type="password" class="form-control" />
        <span asp-validation-for="Password" class="text-danger"></span>
    </div> 

    <!-- Google reCAPTCHA widget -->
    <div class="form-group">
        <div class="g-recaptcha" data-sitekey="YOUR_SITE_KEY"></div>
    </div>

    @{
        if (ViewData["UserNotFoundError"] != null)
        {
                    <div class="alert alert-danger" role="alert">
                        @ViewData["UserNotFoundError"]
                    </div>
        }else
        {
            
        }
    }
    <button id="signInButton" type="submit" class="btn btn-primary">Sign In</button>
    <a class="btn btn-register" asp-area="" asp-controller="Accounts" asp-action="Register">Register</a>
</form>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}
<script src="https://www.google.com/recaptcha/enterprise.js?render=6LciTbQpAAAAAAQZq8mWaytH5-3Y82Hs6_Vll_wi"></script>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

<script>


    function getToken() {
        grecaptcha.enterprise.ready(function () {
            grecaptcha.enterprise.execute('6LciTbQpAAAAAAQZq8mWaytH5-3Y82Hs6_Vll_wi', { action: 'LOGIN' })
                .then(function (token) {
                    console.log("Token: " + token);
                    document.getElementById("LoginViewModelToken").value = token;
                })
                .catch(function (error) {
                    console.error('Error executing reCAPTCHA:', error);
                });
        });
    }


    $(document).ready(function () {
        getToken();

        setInterval(getToken, 115000);

    });

       


</script>

Learning/Views/Accounts/Register.cshtml
@model Learning.Models.LoginModel

@{
    ViewData["Title"] = "Register";
}

<h1>Register</h1>

<h4>LoginModel</h4>
<hr />
<form method="post">

<div class="row">
    <div class="col-md-4">
        <form asp-action="Register">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NID" class="control-label"></label>
                <input asp-for="NID" class="form-control" />
                <span asp-validation-for="NID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                    <button type="submit" class="btn btn-primary" style="width:150px">Register</button>
            </div>
        </form>
    </div>
</div>

<div>
     <a asp-controller="Accounts" asp-action="Login">Back to Sign in</a>
</div>
</form>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Learning/Views/Accounts/UserLogin.cshtml
@model IEnumerable<Invoice>

@{
    ViewData["Title"] = "Home Page";
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <style>
        body {
            margin: 0;
            font-family: Arial, Helvetica, sans-serif;
        }

        .topnav {
            overflow: hidden;
            background-color: #333;
        }

            .topnav a {
                float: left;
                display: block;
                color: #f2f2f2;
                text-align: center;
                padding: 14px 16px;
                text-decoration: none;
                font-size: 17px;
            }

                .topnav a:hover {
                    background-color: #ddd;
                    color: black;
                }

                .topnav a.active {
                    background-color: #4CAF50;
                    color: white;
                }

            .topnav .icon {
                display: none;
            }

        .description {
            text-align: center;
            margin-top: 50px;
            font-style: italic;
            font-size: 24px;
        }

        .invoices-table,
        .contracts-table {
            margin-top: 20px;
            text-align: center;
        }

        .table-wrapper {
            width: 80%;
            margin: 0 auto; /* Center the table horizontally */
            overflow-x: auto; /* Enable horizontal scrolling if needed */
        }

        table {
            width: 100%;
            border-collapse: collapse;
            border-spacing: 0;
        }

        th, td {
            padding: 8px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }

        th {
            background-color: #f2f2f2;
        }

        tbody tr:nth-child(even) {
            background-color: #f2f2f2;
        }

        tbody tr:hover {
            background-color: #ddd;
        }
    </style>
</head>
<body>

    <div class="topnav" id="myTopnav">
        <a class="active" id="homeUser">Home</a>
        <a href="javascript:void(0);" onclick="loadInvoices()">Invoices</a>
        <a href="javascript:void(0);" onclick="loadProfile()">User Profile</a>
    </div>

    <div class="description" id="welcomeMessage">
        <p>Welcome, @ViewData["UserName"].</p>
    </div>

    <div class="profile" id="profile"></div>
    <div class="invoices-table" id="invoicesContent"></div>

    <script>
        function loadInvoices() {
            $("#invoicesContent").show();
            $("#welcomeMessage").hide();
            $("#profile").hide();

            var isAdmin = '@ViewData["isAdmin"]';
            var nid = '@ViewData["NID"]';
            var name = '@ViewData["UserName"]';
            var url = '@Url.Action("Invoice", "Accounts")?isAdmin=' + isAdmin + '&nid=' + nid + '&name=' + name;

            $.get(url, function (data) {
                $("#invoicesContent").html(data);
            });
        }

        function loadProfile() {
            $("#invoicesContent").hide();
            $("#welcomeMessage").hide();
            $("#profile").show();

            var nid = '@ViewData["NID"]';


            var url = '@Url.Action("Index", "Profile")?nid=' + nid;
            $.get(url, function (data) {
                $("#profile").html(data);
            });
        }
    </script>

</body>
</html>